alias ls='ls --color=auto --group-directories-first'
alias la='ls -lha --color=auto --group-directories-first'
alias ll='ls -lh --color=auto --group-directories-first'
alias nv='nvim'
alias vi='nvim'
alias zrc='nvim ~/.zshrc'
alias nrc='nvim ~/.config/nvim/init.vim'
alias explore='explorer.exe .'
alias upug='sudo apt update && sudo apt upgrade'
alias fp='fzf --preview "bat --style=numbers --color=always {}"'
alias nfp='nvim $(fp)'
alias glog='git log | nvim -R -'
alias e='exa -l --git --icons --group-directories-first'
