#!/bin/sh

rm -rf /home/sean/Projects/bit-study-notes/build
ssh sean@192.168.1.254 'rm -rf /share/Web/*'

DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr antora /home/sean/Projects/bit-study-notes/site.yml

if [ -d "/home/sean/Projects/bit-study-notes/build/site" ]; then
    scp -r /home/sean/Projects/bit-study-notes/build/site/* sean@192.168.1.254:/share/Web
else
    echo "Unable to copy to remote"
fi

